name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: [self-hosted, macos]
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Archive app
        run: |
          cd ios
          pwd
          xcodebuild archive \
          -workspace "begun.xcworkspace" \
          -scheme begun \
      - name: Build app
        run: |       
          # find / -name begun.xcworkspace 2>/dev/null
          xcodebuild -workspace begun.xcworkspace -scheme begun archive -archivePath begun.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./begun.xcarchive -exportPath . -exportOptionsPlist begun/Info.plist
          mv begun.ipa ../begun.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: begun.ipa
          path: ios/build/
