name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: [self-hosted, macos]
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Archive app
        run: |
          xcodebuild -workspace ios/begun.xcworkspace -scheme begun -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/begun.xcarchive
      - name: export ipa file
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/begun.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
      - name: upload ipa file 
        run: |
          xcrun altool --validate-app --file $PWD/build/begun.ipa --username vladimir.grigoryan@techflow.studio --password Vlad009277       
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: begun.ipa
          path: ios/build/
