name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: auto increment app version
        run: |
          cd ios && xcrun agvtool new-version -all $GITHUB_RUN_NUMBER
      - name: Run fastlane setup
        env:
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          fastlane setup --verbose
      - name: Run fastlane signing
        run: |
          fastlane match appstore --readonly
      - name: Run fastlane build
        run: |
          pwd; ls; fastlane deploy --verbose
        env:
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
      - name: upload app
        run: |
          xcrun altool --upload-app --file $PWD/build/begun.ipa --username vladimir.grigoryan@techflow.studio --password Vlad009277
