name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: auto increment app version
        run: |
          cd ios && xcrun agvtool new-version -all $GITHUB_RUN_NUMBER
      - name: Run fastlane setup
        env:
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          fastlane setup --verbose
      - name: Run fastlane build
        run: |
          fastlane compile --verbose
        env:
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
          SIGNING_ID: ${{ secrets.SIGNING_ID }}
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
      - name: Archive app
        run: |
          xcodebuild -workspace ios/begun.xcworkspace -allowProvisioningUpdates -scheme begun -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/begun.xcarchive
      - name: export ipa file
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/begun.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
      - name: validate app
        run: |
          xcrun altool --validate-app --file $PWD/build/begun.ipa --username vladimir.grigoryan@techflow.studio --password Vlad009277
      - name: upload app
        run: |
          xcrun altool --upload-app --file $PWD/build/begun.ipa --username vladimir.grigoryan@techflow.studio --password Vlad009277
