# all secrets
# APPLE_ACCOUNT - account for sign in app store
# TEAM_ID - app store team ID
# MATCH_REPO - Repo for app certificate for match usage (you should make it as private)
# MATCH_PASS -  secret environment variable named MATCH_PASSWORD.
# APP_SCHEMA_NAME -  the app name used with xcode.(begun)
# APP_ID -  the app id (mobi.robofruit.run-tracking-app)
# CODE_SIGN_ID -   will find when creating match repo with command  fastlane match appstore - Apple Distribution: Aleksandr Potemkin (74739P8ZK8)

name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: auto increment app version
        run: |
          cd ios && xcrun agvtool new-version -all $GITHUB_RUN_NUMBER
      - name: Run fastlane setup
        env:
          APPLE_ACCOUNT: vladimir.grigoryan@techflow.studio
          TEAM_ID: 74739P8ZK8
          APP_SCHEMA_NAME: begun
          APP_ID: 'mobi.robofruit.run-tracking-app'
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
        run: |
          fastlane setup --verbose
      - name: Run fastlane signing
        run: |
          fastlane compile --verbose
        env:
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
          APPLE_ACCOUNT: vladimir.grigoryan@techflow.studio
          TEAM_ID: 74739P8ZK8
          APP_SCHEMA_NAME: begun
          APP_ID: 'mobi.robofruit.run-tracking-app'
          CODE_SIGN_ID: 'Apple Distribution: Aleksandr Potemkin (74739P8ZK8)'
      - name: Run fastlane build
        run: |
          pwd; ls; fastlane deploy --verbose
        env:
          APPLE_ACCOUNT: vladimir.grigoryan@techflow.studio
          TEAM_ID: 74739P8ZK8
          APP_SCHEMA_NAME: begun
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
          APP_ID: 'mobi.robofruit.run-tracking-app'
          CODE_SIGN_ID: 'Apple Distribution: Aleksandr Potemkin (74739P8ZK8)'
      - name: upload app
        run: |
          xcrun altool --upload-app --file $PWD/build/begun.ipa --username vladimir.grigoryan@techflow.studio --password Vlad009277
